version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - mkdir -p docs/notebooks
      - find docs/notebooks -type f -name "*.ipynb" ! -name "index.ipynb" -delete
      - cp notebooks/*.ipynb docs/notebooks/ || true

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

