version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - mkdir -p docs/notebooks
      - find docs/notebooks -mindepth 1 -delete
      - find notebooks -maxdepth 1 -name "*.ipynb" -exec cp -t docs/notebooks {} +

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

